from z3.z3util import get_vars
from z3 import SolverFor, ForAll, Implies
from presentation_forms import vertically, table_repr, Legend


class CHCs:
    """
    A system of CHC rules.
    """
    def __init__(self, rules: list=None, predicate_symbols: set=None):
        self.rules = rules or []
        self.predicate_symbols = predicate_symbols or set()
        self.predicate_symbols_ids = set(u.get_id() for u in self.predicate_symbols)
    
    def __iadd__(self, more_rules: list):
        self.rules += more_rules
        return self
    
    def _repr_html_(self):
        return vertically(self.rules)._repr_html_()
    
    @property
    def freevars(self):
        return set(v for rule in self.rules for v in self.freevars_of(rule))
                         
    def freevars_of(self, rule):
        return [v for v in get_vars(rule)
                if v.decl().get_id() not in self.predicate_symbols_ids and  # the condition is needed!
                   v.get_id() not in self.predicate_symbols_ids]
    
    @property
    def relations(self):
        return self.U.values()
    
    def to_quantified(self):
        def forall_tentative(vs, body):
            return ForAll(vs, body) if vs else body
        return [forall_tentative(self.freevars_of(r), r) for r in self.rules]
    
    def create_solver(self, theory="HORN", engine=None):
        s = SolverFor(theory)
        if engine: s.set('engine', engine)
        for phi in self.to_quantified(): s.add(phi)
        return s
    
    @classmethod
    def query(cls, q):
        return [Implies(q, False)]


    

class HyperResolutionProof(object):
    """
    Used to inspect a proof of unsat generated by Spacer.
    Visualizes proof steps as a directed graph.
    """

    def __init__(self, pf_ast):
        self._ast = pf_ast

    def _get_premises_and_conclusion(self, hrstep):
        ch = hrstep.children()
        return ch[:-1], ch[-1]

    def _get_conclusion(self, hrstep):
        return self._get_premises_and_conclusion(hrstep)[1]

    def _traverse(self, ast, cb, visited):
        if ast in visited:
            return

        visited.add(ast)

        subgoals, conclusion = self._get_premises_and_conclusion(ast)
        premises = [self._get_conclusion(k) for k in subgoals]
        
        if conclusion not in visited:
            cb['conjecture'](conclusion)
            visited.add(conclusion)
        
        for (subgoal, premise) in zip(subgoals, premises):
            self._traverse(subgoal, cb, visited)
            cb['dependency'](premise, conclusion)
            
        cb['inference'](premises, conclusion)

    def to_dot(self):
        import graphviz
        g = graphviz.Digraph()

        key = lambda phi: str(phi.get_id())
        
        cb = {
            'conjecture': lambda phi: g.node(key(phi), str(phi)),
            'dependency': lambda phi, psi: g.edge(key(phi), key(psi)),
            'inference':  lambda phis, psi: None
        }
        
        self._traverse(self._ast, cb, set())
        return g
    
    def to_roadmap(self):
        # @todo DRY definitely some duplication here
        import graphviz
        g = graphviz.Digraph()
        
        leg = Legend(by = lambda phi: phi.get_id())
        key = lambda phi: str(leg.key(phi))
        
        cb = {
            'conjecture': lambda phi: g.node(key(phi), key(phi)),
            'dependency': lambda phi, psi: g.edge(key(phi), key(psi)),
            'inference':  lambda phis, psi: None
        }

        self._traverse(self._ast, cb, set())

        trep = table_repr([[g, leg]])
        trep.col_styles[0] = 'width: 20%'
        return trep

    def _repr_svg_(self):
        return self.to_dot()._repr_svg_()

    def __str__(self):
        return str(self.to_dot())
    def raw(self):
        return self._ast

    